import Navbar from '@/components/layout/Navbar';
import Footer from '@/components/layout/Footer';
import { LEGAL_CONFIG } from '@/lib/legalConfig';
import styles from '@/components/portfolio/portfolio.module.css';
export const metadata = { title: 'Privacy notice · TejAi' };
export default function Privacy() { return <><Navbar /><main className={styles.page}>
  <p className={styles.eyebrow}>Portfolio privacy notice · September 11, 2026</p><h1 className={styles.title}>What the project stores.</h1>
  <div className={styles.card}>
    <h2>Sample workspace</h2><p className={styles.lead}>The demo contains synthetic data. Only its sample clock and check-in choices are stored in your browser under tejai.demo.v1. Reset demo clears those choices. The demo does not initialize account authentication or call the live API. Hosting still receives ordinary page and asset requests.</p>
    <h2>Live account and routines</h2><p className={styles.lead}>Google and GitHub sign-in are handled by Supabase. The live application uses your account identifier and email, stores session credentials through the authentication client, and saves your timezone, routine check-ins and normalized analysis results. Real routine and scan records are not cached in browser storage by this application.</p>
    <h2>Optional portrait processing</h2><p className={styles.lead}>When live scanning is enabled, an adult user must explicitly consent before uploading a portrait. The Express API validates and normalizes the JPEG in memory, strips metadata and sends it to Face++ using its US endpoint. The application saves normalized observations, not the original portrait, raw response or face tokens. Buffers are cleared when processing ends. Images are not used to identify a person or build a face-search collection.</p>
    <h2>External provider and location</h2><p className={styles.lead}>Face++ is an external processor with its own processing and retention terms. The application cannot guarantee that the provider immediately deletes a portrait. Live scanning remains disabled until the operator has reviewed those terms and verified access. This deployment does not promise EU-only processing. Review the provider’s <a href="https://www.faceplusplus.com/privacy-policy/" target="_blank" rel="noreferrer">privacy policy</a> before choosing to upload.</p>
    <h2>Controls and retention</h2><p className={styles.lead}>Withdraw scan consent in Settings, delete a saved result from its page, or delete your account after identity confirmation. Withdrawal does not delete previous records. Account deletion removes routine preferences and check-ins with the account. Anonymous provider-attempt records become eligible for deletion after 90 days. Cleanup runs on later scan requests; an inactive deployment needs manual cleanup. Limited pseudonymous deletion audits follow the operator’s configured retention period (365 days by default) and require the documented purge procedure. Hosting and provider records follow their own policies.</p>
    <h2>Contact</h2><p className={styles.lead}>{LEGAL_CONFIG.privacyEmail ? <a href={`mailto:${LEGAL_CONFIG.privacyEmail}`}>{LEGAL_CONFIG.privacyEmail}</a> : 'A private privacy contact must be configured before opening live access to the public. Please do not post portraits, tokens or personal account information in public GitHub issues.'}</p>
  </div></main><Footer /></>; }
